# Generated by Django 4.1.5 on 2023-02-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('editorial', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('año', models.IntegerField()),
                ('puntaje', models.IntegerField()),
                ('reseña', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('año', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='novedades')),
            ],
        ),
    ]
