# Generated by Django 4.1.5 on 2023-02-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='editorial',
            new_name='autorLib',
        ),
    ]
